### ISSUE TITLE
Suggestion: Coveralls

### ISSUE THREAD

**Issue by soullivaneuh** [Algatux/influxdb-bundle#14]
I suggest you to setup Coveralls: https://coveralls.io/

With this tools, you will get PR status for coverage.

Example:

![image](https://cloud.githubusercontent.com/assets/1698357/15777958/6a82a0c8-2993-11e6-82b1-7801678293e9.png)

**Comment by Algatux** [comment]
Used before scrutinizer. The last does the same job and is ok

**Comment by soullivaneuh** [comment]
Pushed button to fast. I updated the description. :+1: 

> Used before scrutinizer. The last does the same job and is ok

Yeah, but what about PR status?

**Comment by Algatux** [comment]
Did not know about this feature. Must look at it again

**Comment by Algatux** [comment]
Must add this check

**Comment by Algatux** [comment]
@Soullivaneuh added but it still not run coverage tests ...

**Comment by soullivaneuh** [comment]
This works on #57, but you should remove PR comment option as I suggested in https://github.com/Algatux/influxdb-bundle/pull/57#issuecomment-238167395.
