### ISSUE TITLE
Abstract prefix for abstract classes

### ISSUE THREAD

**Issue by soullivaneuh** [Algatux/influxdb-bundle#28]
According to the [Symfony Coding Standards](http://symfony.com/doc/current/contributing/code/standards.html#naming-conventions):

> Prefix abstract classes with Abstract. Please note some early Symfony classes do not follow this convention and have not been renamed for backward compatibility reasons. However all new abstract classes must follow this naming convention;

Do you want to follow this rule?

We can take profit of the next major to rename the concerned class.

**Comment by Algatux** [comment]
Yes I actually follow this convention. For me its ok
