### ISSUE TITLE
Why make the listener optional?

### ISSUE THREAD

**Issue by soullivaneuh** [Algatux/influxdb-bundle#31]
Does the `use_events` configuration very useful? Why did you make the listener optional?

**Comment by Algatux** [comment]
If unused why register it ?

**Comment by soullivaneuh** [comment]
If unused, just don't call him.

AFAIK, event-listener are lazy loaded. I never see any bundle having option to activate/deactivate the service. I'm not sure it really adds benefit.

**Comment by soullivaneuh** [comment]
@Algatux Could we remove this option or not?

I have to know in order to continue #21.

**Comment by Algatux** [comment]
Yess you are right about lazy listeners

**Comment by soullivaneuh** [comment]
So, can we remove this option?

**Comment by Algatux** [comment]
Yeah. No more option. Listerer registred always
