### ISSUE TITLE
Database creation should not offer "if not exists"

### ISSUE THREAD

**Issue by curry684** [Algatux/influxdb-bundle#66]
The "if not exists" syntax in Database::create was defaulted and deprecated before 1.0 release, and crashes with syntax error if used now. The parameter should be removed.

**Comment by Algatux** [comment]
@curry684 Thanks to reporting this issue, I'm actually not understanding what are you referring to.
Can you be more precise about the problem and where you found it ?

thanks a lot again.

**Comment by curry684** [comment]
Mmmm I should be ashamed, the issue belongs with the library, not the bundle.

Closed in favor of https://github.com/influxdata/influxdb-php/issues/67, my apologies.
