### ISSUE TITLE
Add support for symfony 4

### ISSUE THREAD

**Issue by Algatux** [Algatux/influxdb-bundle#74]
- [X] blocked by matthiasnoback/symfony-dependency-injection-test
- [x] blocked by influxdb/influxdb-php (fix is on master, waiting for release)
- [x] fix services visibility for symfony 3.3 / 4.*
- [x] update composer.json requirements

**Comment by curry684** [comment]
Upstream is compatible now  😉

**Comment by salvatorecordiano** [comment]
@Algatux `influxdb/influxdb-php` is blocking your upgrade. It requires `symfony/event-dispatcher: 2.*|3.*`

**Comment by pepijnblom** [comment]
`influxdb/influxdb-php` requires `"symfony/event-dispatcher": "^2.0 || ^3.0 || ^4.0"` since 18 november in [this commit](https://github.com/influxdata/influxdb-php/commit/8fcc54417667e9b7c1b7d1cd861e8420f113226a#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780)

**Comment by Algatux** [comment]
@salvatorecordiano is working on this issue

**Comment by Algatux** [comment]
@salvatorecordiano, a new version of influxdb/influxdb-php has been released!

**Comment by Algatux** [comment]
closed with pr #75
