### ISSUE TITLE
Field key query failing

### ISSUE THREAD

**Issue by Jerome1337** [Algatux/influxdb-bundle#76]
When creating measurement field inside a form, the current query to get `fieldKey` seem to be broken
cf : https://github.com/Algatux/influxdb-bundle/blob/master/src/Form/Type/FieldKeyType.php#L26

Then we get this error : 
```
unable to use system source '_fieldKeys': use SHOW FIELD KEYS instead
```

**Comment by Algatux** [comment]
@Jerome1337 Hi! Is this issue related to a specific version of influxdb ?

**Comment by Jerome1337** [comment]
@Algatux Hi, I don't think. I tried with `1.0` and `1.4`
