### ISSUE TITLE
[Deprecation] deprecate usage of php 7.0

### ISSUE THREAD

**Issue by Algatux** [Algatux/influxdb-bundle#88]
Enforce usage of php 7.1 inside composer.json and release a new major

**Comment by soullivaneuh** [comment]
No need of a major for that if you don't change your public API: https://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api

**Comment by Algatux** [comment]
I know that, but I was thinking that a major will be more "secure" :P

**Comment by soullivaneuh** [comment]
How it will be more secure?

If the end user do a composer update under PHP 7.0, composer will just not update your bundle.

If you really want a major, go ahead! But I can ensure you it is pointless. :wink:

**Comment by soullivaneuh** [comment]
But if you do a new major, you may consider #62.

**Comment by Algatux** [comment]
@Soullivaneuh no you are right, composer is already protecting from upgrading
