### ISSUE TITLE
The ports configuration should a an int, not a string

### ISSUE THREAD

**Issue by soullivaneuh** [Algatux/influxdb-bundle#9]
You use them (udp and tcp) as strings, but according to the `Client` class: https://github.com/influxdata/influxdb-php/blob/1.4.1/src/InfluxDB/Client.php#L101

They should be integers.

But, because you are using strict typing, changing that would be BC break.

So this issue need to be solved on next major.

**Comment by Algatux** [comment]
Yes it's my fault :cry:  @Soullivaneuh

**Comment by soullivaneuh** [comment]
After reflection, this can be done on a BC way:
- Remove strict typing for ports parameters
- Trigger a deprecation warning if a string is passed
- Trigger an error if the parameter is not a int nor a string
- Push a new minor
- Restore strict typing for ports parameters
- Push a new major

What do you think?
