### ISSUE TITLE
warning: Deprecated use of Drop database in a read only context

### ISSUE THREAD

**Issue by dmitry84** [Algatux/influxdb-bundle#91]
Hi 
I got the following error when tried to remove DB.

The code:
 $this->influxConnection->query('Drop Database ....');

DB is removed, but as a result, I got the following error (see below full output).

I can not find any mentions in the documentation on how to change the mode for the connection or query.

influxdb-bundle: 2.4.0

unfortunately can not find the influx version, but should be latest or very close to the latest (I have access only via SQL or via Chronograf)

Full error message:

```
object(InfluxDB\ResultSet)#1067 (2) {
  ["parsedResults":protected]=>
  array(1) {
    ["results"]=>
    array(1) {
      [0]=>
      array(2) {
        ["statement_id"]=>
        int(0)
        ["messages"]=>
        array(1) {
          [0]=>
          array(2) {
            ["level"]=>
            string(7) "warning"
            ["text"]=>
            string(128) "deprecated use of 'DROP DATABASE XXXXX' in a read only context, please use a POST request instead"
          }
        }
      }
    }
  }
  ["rawResults":protected]=>
  string(204) "{"results":[{"statement_id":0,"messages":[{"level":"warning","text":"deprecated use of 'DROP DATABASE XXXXX' in a read only context, please use a POST request instead"}]}]}
"
}
```

**Comment by Algatux** [comment]
@dmitry84 I have to investigate this issue, in the meantime can you try to use the 'algatux:influx:database:drop' provided console command to do the same thing

**Comment by Algatux** [comment]
@dmitry84 delete operation that you are trying to perform seems to be deprecated from at least mid 2016. I thin you cannot use the query method. instead, try with drop as we do inside our command.

**Comment by dmitry84** [comment]
Thank you @Algatux

I'll try to test this during the weekend and let you know.
