### ISSUE TITLE
How to use this extension with new EventDispatcherInterface

### ISSUE THREAD

**Issue by odombrovskyi-dev** [Algatux/influxdb-bundle#94]
Hi, when I use your bundle in my project I get always this deprecation notice:

`
User Deprecated: Calling the "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" method with the event name as the first argument is deprecated since Symfony 4.3, pass it as the second argument and provide the event object as the first argument instead.
`

Do you know how to adjust it? I checked your code and InfluxDbEventListener is subscribed to the event with name `influxdb.points_collected` and it's impossible to use  EventDispatcherInterface in a new way like this:

```
        $this->eventDispatcher->dispatch(new UdpEvent([$point], Database::PRECISION_SECONDS));
```

Do you have any suggestions?

**Comment by Algatux** [comment]
Hi @adombrovsky, which version of Symfony are you using actually?

I've to investigate the issue.

Can't you try by passing the event name as second argument ? 

$this->eventDispatcher->dispatch(new UdpEvent([$point], Database::PRECISION_SECONDS), InfluxDbEvent::NAME);

**Comment by odombrovskyi-dev** [comment]
Hi @Algatux , sorry for long delay. I checked your suggestion and deprecation warning is not showing anymore. Thanks for the help.
