### ISSUE TITLE
Support PHP 8

### ISSUE THREAD

**Issue by TPete** [Algatux/influxdb-bundle#96]
Currently the bundle can't be used on PHP 8 because of the version constraint. Please consider supporting PHP 8 as well.

From a quick check your dependencies all support PHP 8, so they won't stop you from upgrading. Not sure about the actual code though.

**Comment by Algatux** [comment]
Hi @TPete, sorry for the delay in the response. 
I'm not actively maintaining the bundle anymore. But as an OS project, it is open to PRs and I will be really happy if someone would send one.

**Comment by soullivaneuh** [comment]
@Algatux I suggest to keep this issue open until some-one propose a solution.

**Comment by artem-yakymchuk-paysera** [comment]
I created PR with symfony 8 support. 
Could you check it please?
https://github.com/Algatux/influxdb-bundle/pull/98
@soullivaneuh 
@Algatux
